const nullableString = { anyOf: [{ type: "string" }, { type: "null" }] } as const;
const nullableNumber = { anyOf: [{ type: "number" }, { type: "null" }] } as const;

export const openApiSchemas = [
  {
    $id: "SafeConnection",
    type: "object",
    additionalProperties: false,
    description:
      "Public connection identity and health. Credential material and its internal secret reference are never present.",
    required: [
      "id",
      "platform",
      "x_account_id",
      "username",
      "display_name",
      "profile_image_url",
      "connection_status",
      "token_expires_at",
      "last_synced_at",
      "last_error",
      "created_at",
      "updated_at",
    ],
    properties: {
      id: { type: "string", description: "Stable internal connection ID." },
      platform: { const: "x", description: "Social platform discriminator." },
      x_account_id: { type: "string", description: "Immutable account ID detected by X." },
      username: { type: "string", description: "Current X handle without @." },
      display_name: { type: "string", description: "Current X display name." },
      profile_image_url: {
        ...nullableString,
        description: "Profile image URL when X supplies it.",
      },
      connection_status: {
        enum: ["connected", "disconnected", "expired", "error"],
        description: "Current credential/sync health.",
      },
      token_expires_at: {
        ...nullableString,
        description: "Access-token expiration in ISO 8601, when known.",
      },
      last_synced_at: { ...nullableString, description: "Last successful durable analytics sync." },
      last_error: { ...nullableString, description: "Sanitized latest connection error." },
      created_at: { type: "string", description: "Connection creation time." },
      updated_at: { type: "string", description: "Connection update time." },
    },
  },
  {
    $id: "AccountSnapshot",
    type: "object",
    additionalProperties: false,
    required: ["account_id", "captured_at", "followers", "following", "total_posts", "listed"],
    properties: {
      account_id: { type: "string", description: "Immutable X account ID." },
      captured_at: { type: "string", description: "When this historical snapshot was captured." },
      followers: { ...nullableNumber, description: "Follower count." },
      following: { ...nullableNumber, description: "Following count." },
      total_posts: { ...nullableNumber, description: "Lifetime post count reported by X." },
      listed: { ...nullableNumber, description: "Number of X lists containing the account." },
    },
  },
  {
    $id: "PostMetric",
    type: "object",
    // Current-metric responses extend a stored snapshot with derived rates.
    additionalProperties: true,
    required: [
      "account_id",
      "post_id",
      "captured_at",
      "age_seconds",
      "impressions",
      "likes",
      "replies",
      "reposts",
      "quotes",
      "bookmarks",
      "profile_clicks",
      "url_clicks",
      "user_profile_clicks",
      "total_engagements",
    ],
    properties: {
      account_id: { type: "string", description: "Owning X account ID." },
      post_id: { type: "string", description: "X post ID." },
      captured_at: { type: "string", description: "Snapshot capture time." },
      age_seconds: { ...nullableNumber, description: "Post age when captured." },
      impressions: { ...nullableNumber, description: "Impressions, or null when unavailable." },
      likes: { type: "number", description: "Likes." },
      replies: { type: "number", description: "Replies." },
      reposts: { type: "number", description: "Reposts/retweets." },
      quotes: { type: "number", description: "Quote posts." },
      bookmarks: { ...nullableNumber, description: "Bookmarks, or null when unavailable." },
      profile_clicks: {
        ...nullableNumber,
        description: "Profile clicks, or null when unavailable.",
      },
      user_profile_clicks: {
        ...nullableNumber,
        description: "X's user_profile_clicks value; alias of profile_clicks.",
      },
      url_clicks: { ...nullableNumber, description: "URL clicks, or null when unavailable." },
      total_engagements: {
        ...nullableNumber,
        description: "Sum of all available engagement actions.",
      },
    },
  },
  {
    $id: "DerivedRates",
    type: "object",
    additionalProperties: false,
    required: [
      "engagement_rate",
      "like_rate",
      "reply_rate",
      "repost_rate",
      "click_through_rate",
      "profile_visit_rate",
    ],
    properties: {
      engagement_rate: {
        ...nullableNumber,
        description: "Total engagements divided by impressions.",
      },
      like_rate: { ...nullableNumber, description: "Likes divided by impressions." },
      reply_rate: { ...nullableNumber, description: "Replies divided by impressions." },
      repost_rate: { ...nullableNumber, description: "Reposts divided by impressions." },
      click_through_rate: { ...nullableNumber, description: "URL clicks divided by impressions." },
      profile_visit_rate: {
        ...nullableNumber,
        description: "Profile clicks divided by impressions.",
      },
    },
  },
  {
    $id: "StoredPost",
    type: "object",
    additionalProperties: true,
    required: [
      "account_id",
      "post_id",
      "text",
      "created_at",
      "url",
      "lang",
      "kind",
      "is_reply",
      "is_quote",
      "is_repost",
      "media_types",
      "contains_url",
      "urls",
      "hashtags",
      "mentions",
      "conversation_id",
      "possibly_sensitive",
      "first_seen_at",
      "updated_at",
    ],
    properties: {
      account_id: { type: "string", description: "Owning X account ID." },
      post_id: { type: "string", description: "X post ID." },
      text: { type: "string", description: "Complete original post text." },
      created_at: { ...nullableString, description: "Original publication time." },
      url: { type: "string", description: "Canonical x.com post URL." },
      lang: { ...nullableString, description: "Language code supplied by X." },
      kind: {
        enum: ["original", "reply", "retweet", "quote"],
        description: "Primary post format.",
      },
      is_reply: { type: "boolean", description: "Whether the post replies to another post." },
      is_quote: { type: "boolean", description: "Whether the post quotes another post." },
      is_repost: { type: "boolean", description: "Whether the post is a repost." },
      media_types: {
        type: "array",
        items: { type: "string" },
        description: "Attached media types such as photo, video, or animated_gif.",
      },
      contains_url: {
        type: "boolean",
        description: "Whether text/entities contain an outbound URL.",
      },
      urls: { type: "array", items: { type: "string" }, description: "Expanded URLs." },
      hashtags: { type: "array", items: { type: "string" }, description: "Hashtags without #." },
      mentions: {
        type: "array",
        items: { type: "string" },
        description: "Mentioned usernames without @.",
      },
      conversation_id: { ...nullableString, description: "X conversation ID." },
      possibly_sensitive: {
        anyOf: [{ type: "boolean" }, { type: "null" }],
        description: "X sensitive-content flag.",
      },
      first_seen_at: { type: "string", description: "First durable ingestion time." },
      updated_at: { type: "string", description: "Most recent metadata refresh." },
    },
  },
  {
    $id: "CurrentPostMetric",
    type: "object",
    additionalProperties: true,
    description: "All PostMetric fields plus all DerivedRates fields for the latest snapshot.",
  },
  {
    $id: "PostAnalytics",
    type: "object",
    additionalProperties: true,
    description: "All StoredPost fields plus the latest metrics and relative performance.",
    properties: {
      metrics: { anyOf: [{ $ref: "CurrentPostMetric#" }, { type: "null" }] },
      performance_relative_to_recent_average: {
        ...nullableNumber,
        description:
          "Post engagements divided by average engagements for posts in the requested window; 1.0 equals average.",
      },
    },
  },
] as const;
